package org.oregonccpt.occpt.ui.officers

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import org.oregonccpt.occpt.R
import org.oregonccpt.occpt.databinding.FragmentOfficersBinding

class OfficersFragment : Fragment() {

    private var _binding: FragmentOfficersBinding? = null
    private val binding get() = _binding!!

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentOfficersBinding.inflate(inflater, container, false)

        val officers = listOf(
            Officer("Sabi Velasco", "Chief Operating Officer (COO)", R.drawable.sabi, "oregonccpt132@gmail.com", "971-998-2730", "My name is Sabi Velasco and I am originally from Mexico from the state of Oaxaca. I have 5 children and I am proud to have a large family. I have more than 26 years working in early education. I have more than 12 years running my child care program. One of the reasons I am part of this field is because today's children need socio-emotional help and being in my program we can work with the family and the children. When children are emotionally regulated they are successful in school and in their lives. One of the main reasons I am on the board is so that all providers from all different languages have representation and have a voice each and every one of us is the union should be heard."),
            Officer("Anneliese Sheahan", "Chief Financial Officer (CFO)", R.drawable.anneliesse_photo, "PILLARSofOregon@gmail.com", "971-204-9110", "Anneliese Sheahan, Licensed Family CF Child Care Gladstone, OR. Specializing in infant and toddler care for children under 2. In the early childhood field since 1994. Graduate of UWSP. Currently pursuing my Juris Doctorate at Purdue Global (yes, that same Purdue University just online). I opened my first licensed family child care in 2002. Advocate at the state and federal level since 2004. I moved to Oregon in March of 2018, and was the staff rep for the local for just over 3 years before transitioning back into owning a licensed family child care. My passion is helping family child care providers -- any way I can! Please give me a call anytime -- I am always here to chat, to assist, to provide training, to lend an empathetic ear and do whatever Ican for my fellow family child care providers. I believe a strong support for child care providers makes a significant impact in our lives, our businesses and our child care industry -- it is because we have strong support for our child care providers that we have a strong family child care workforce. Come join me on FB at PILLARS -- our public page. u -- with legal standing to be your legally recognized representative. Please reach out and contact me if you need our help. I am not an attorney and cannot give legal advice, but I will fight for you, your reputation, your business, your staff, and your clients. We stand together -- you don't have to go it alone. While an attorney knows the law, they don't know the child care system, they likely don't know administrative laws, and they won't give you the time, attention, and communion you deserve. We support you, the whole you - not just your case. <3"),
            Officer("Vanessa Brown", "Secretary", R.drawable.vannessa_brown, "littleswanschildcarekf@gmail.com", "541-892-3335", "I'm Vanessa, I have been a Union member since 2017 and have been a Board Member since 2018. Currently, I am the Executive Board Secretary, Union Shop Steward, Organizing Committee Chair and Merchandise Committee Chair. I own a Certified Family In Home Child Care in Klamatch Falls. As a Union Leader, I take pride in representing our Licensed Child Care Providers in Oregon. The work child care providers in Oregon do is invaluable and we are so under appreciated. I think it is important that you know, we the Executive Board, care about you and value what you do every day! Please reach out to me if you need any help."),
            Officer("Sheila Ullom", "Chief Technology Officer (CTO)", R.drawable.sheila_ullom_2, "LPChildCare@yahoo.com", "541-643-6309", "I’m Sheila, and I am very proud to be a founder owner/member of PILLARS. This spring (2026) I will finish my Associates in Early Childhood Development and will continue to work on my Bachelors at SOU. I have 10 years of experience as a child care provider, and over 15 years experience working with children. My journey into this field started because I believe that every child deserves a nurturing 'home away from home' and every provider deserves a community that actually has their back. I joined the board because I wanted to make sure our voices aren't just heard, but celebrated. When I’m not working, doing homework or writing, you can usually find me gaming with my online friends. I’m here to listen, support, and maybe share a laugh when the day gets long. We’re in this together, and I can’t wait to see everything we’ll accomplish for Oregon’s families!"),
            Officer("Alisha Cox", "Owner/Member", R.drawable.alisha_cox, null, null, "My name is Alisha (Cox) Hendrickson. I am married and have 5 children and 3 step-children. I have been working with children and families since 2007. I have a Bachelor of Science in Early Childhood and I am a step 10 on the Oregon Registry. I began my journey in childcare at a private preschool in Utah while I was finishing my Bachelor of Science in Early Childhood at Weber State University. Shortly after graduation I moved to Oregon to be closer to family. I worked as a Lead Teacher for Head Start in Lebanon, OR for two years. After my family grew in 2012, I wanted to be home to raise them and give them the wonderful experiences I was giving to my Head Start children. I became a small Registered Family provider and then became a Certified Family Provider in 2016. I will always cherish the opportunity family childcare has given me to raise my children in the safety and security of my own home. I became a member of the union shortly after becoming licensed but I didn't really know anything about what that involved or what the benefits were. After the massive restrictions and rule changes that came with Covid and that continue to be pushed by the state, I wanted to get more involved. I am a founding member/owner of PILLARS. My passion for advocacy has only grown since joining. I have learned so much about the ins and outs of policy and rule making and I am learning about the complexities of both running a program, advocating for providers. In this position I am hoping to increase involvement and networking in my region. I would like PILLARS to be strong and active and I believe that starts with personal connections."),
            Officer("Amber Oldridge", "Owner/Member", R.drawable.amberopic, null, null, "provider in Grants Pass, Oregon. I am originally from Sacramento, California, I began my career in healthcare in 2006. Since second grade, I have always wanted to work with children. I initially aimed to become a school teacher, but due to a speech impediment, I chose to focus on children instead. I started as a teacher's aide and worked my way up to a lead teacher then, lastly a assistant director at a center. In December 2016, I moved to Oregon and took a break from working with children. However, I quickly realized how much I missed it. This inspired me to buy a house and establish my own program, Home from Home Family Preschool and Childcare. About a year ago, I joined the union as second vice president, and while I have much more to learn, I have already gained valuable knowledge. I am proud to be part of Local 132, where I work with amazing group of women and men dedicated to fighting for equality, fairness, and what is right for all providers. I love that, despite our diverse backgrounds—whether ethnic, linguistic, or economic—we come together to collaborate and advocate for all childcare providers."),
            Officer("Michael Ullom", "Owner/Member", R.drawable.michael_ullom, null, null, "Coming Soon."),
            Officer("Candy Clinkenbeard", "Owner/Member", R.drawable.occpt_app_icon_5, null, null, "We are waiting for Candy bio and photo check back soon! ;)"),
            Officer("Kimberly Hess", "Owner/Member", R.drawable.occpt_app_icon_5, null, null, null),
            Officer("Zack Wolchesky", "Owner/Member", R.drawable.occpt_app_icon_5, "wolchesky@gmail.com", "971-356-5167", "My name is Zack. I'm located in Clackamas County. It's very hard being a man in the child care field. We have all the same issues as other family child care providers but on top of that we face social stigma and always the questions about why we are in child care. I'm here on our board to break down those social stereotypes and stand up for men in child care. I have 3 children of my own plus my son in-law. They all mooch off of me but I have them all working for me in my child care. I first joined CCPT in Wisconsin in 2007. I joined CCPT in Oregon in 2019. Please reach out to me from anywhere in the state -- the counties I represent (with Julie Anderson) are Multnomah, Clackamas, Wasco, Hood, and Gilliam. Please let me know if you would like to have a local meeting in your county/city, have a training, have a Zoom meeting, or anything else we can do for our members in Oregon."),
            Officer("Malgorzata (Gosia Patton)", "Owner/Member", R.drawable.occpt_app_icon_5, null, null, null),
            Officer("Ana Rivera", "Owner/Member", R.drawable.occpt_app_icon_5, null, null, null),
            Officer("Caravantes Orozco", "Owner/Member", R.drawable.occpt_app_icon_5, null, null, null),
            Officer("Courtney Janos", "Owner/Member", R.drawable.occpt_app_icon_5, null, null, null),
            Officer("Ashley Crouch", "Owner/Member", R.drawable.occpt_app_icon_5, null, null, null),
            Officer("Lisa Duffield", "Owner/Member", R.drawable.occpt_app_icon_5, null, null, null),
            Officer("Oriana Wolchesky", "Owner/Member", R.drawable.occpt_app_icon_5, null, null, null),
            )

        val adapter = OfficersAdapter(officers)
        binding.officersRecyclerView.adapter = adapter

        return binding.root
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}